# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffed8614f1a01c35dfec0df3ab922c2c022ed60c3a553310215c834ae5a5a0912b4c7410c2b0df5d40539c6ea67307752c5180e858686c4fd463f0965d228b1a

test:
  secret_key_base: 823bf476a8fd605be17778f9110eb32dae0e77beb8565af2ec32f3eeba2419322253c065486631abe233faaf0467e4a527113c5039f523fc2b368f4212a49fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
